# CRT-TBS Strategy Configuration

strategy_name: "CRT_TBS"
version: "1.0.0"

# Timeframe Selection
timeframes:
  scalping:
    htf: "1H"
    ltf: "1m"
  intraday:
    htf: "1D"
    ltf: "1H"
  selected: "intraday"  # Change as needed

# CRT Detection
crt_detection:
  method: "body_vs_wicks"  # body > upper_wick + lower_wick
  alternative_ratio: null  # Optional: 0.50 for 50% body minimum

# Key Level Detection
keylevel_detection:
  ohp_olp:
    lookback:
      "1H": 20
      "4H": 15
      "1D": 10
    swing_detection:
      left: 2
      right: 2
  
  fvg:
    minimum_gap_percent: 0.05  # 0.05% = 5 basis points
  
  order_block:
    min_consecutive_candles: 5
  
  rejection_block:
    min_wick_ratio: 0.40

# TBS Detection
tbs_detection:
  allow_multi_candle: true
  valid_range: [2, 6]  # A+ TBS patterns

# Model #1 Detection
model1_detection:
  method: "body_vs_wicks"  # Same as CRT
  max_wait_candles:
    "1m": 10
    "5m": 10
    "1H": 8

# Risk Management
risk_management:
  risk_per_trade_percent: 1.0
  minimum_rr_ratio: 1.5
  position_scaling: [0.5, 0.5]
  breakeven_trigger: "after_tp1"
  
  portfolio:
    max_concurrent_positions: 3
    daily_loss_limit_percent: null  # Optional: 3.0 = -3%

# Trade Execution (Document-Specified)
execution:
  stop_loss:
    placement: "exact_extreme"
    buffer: 0  # No buffer per documentation
  
  take_profit:
    tp1_percent: 0.50  # 50% of CRT range
    tp2_percent: 1.00  # 100% of CRT range

# Filters (Document-Specified: NONE)
filters:
  session: false
  time_of_day: false
  news: false
  volatility: false

# Backtesting Parameters
backtesting:
  optimization_params:
    test_crt_ratio: [0.50, 0.55, 0.60]
    test_lookback_1h: [15, 20, 25, 30]
    test_lookback_4h: [10, 15, 20]
    test_lookback_1d: [8, 10, 12, 15]
    test_min_rr: [1.3, 1.5, 1.8, 2.0]
    test_model1_timeout: [6, 8, 10, 12]
